### ISSUE TITLE
Android6.0手机小米5sp运行错误

### ISSUE THREAD

**Issue by jackuhan** [dodola/AnoleFix#3]
05-21 19:22:19.241 12235-12235/dodola.anole W/System: ClassLoader referenced unknown path: /data/app/dodola.anole-1/lib/arm64
05-21 19:22:19.243 12235-12235/dodola.anole V/!!Anole!!: Got the list of classes 
05-21 19:22:19.243 12235-12235/dodola.anole V/!!Anole!!: class dodola.anole.a
05-21 19:22:19.243 12235-12235/dodola.anole V/!!Anole!!: class dodola.anole.b
05-21 19:22:19.247 12235-12235/dodola.anole W/System.err: java.lang.ClassNotFoundException: Didn't find class "dodola.anole.a" on path: DexPathList[[zip file "/data/user/0/dodola.anole/files/hotfix/patch.jar"],nativeLibraryDirectories=[/data/app/dodola.anole-1/lib/arm64, /vendor/lib64, /system/lib64]]
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at dodola.anole.runtime.AbstractPatchesLoaderImpl.load(AbstractPatchesLoaderImpl.java:34)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at dodola.anole.lib.Anole.applyPatch(Anole.java:57)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at dodola.anole.MainActivity$1.onClick(MainActivity.java:26)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at android.view.View.performClick(View.java:5207)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at android.view.View$PerformClick.run(View.java:21177)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at android.os.Looper.loop(Looper.java:148)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5458)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
05-21 19:22:19.248 12235-12235/dodola.anole W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by jackuhan** [comment]
测试了Android4.2 & 5.0 & 6.0系统的手机，全部报相同错误。
